In [9]:
#question 01 apply svm and find acccuracy(using libraries)
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score

# 1. Social Network Ads
df = pd.read_csv('Social_Network_Ads.csv')
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
X = df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Social Network Ads Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


# 2. Titanic
df = pd.read_csv('titanic.csv')
df = df[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
df['Sex'] = LabelEncoder().fit_transform(df['Sex'].astype(str))
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'].astype(str))
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df = df.dropna()
X = df.drop('Survived', axis=1).values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Titanic Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


# 3. Diabetes
df = pd.read_csv('diabetes_dataset.csv')
X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Diabetes Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Social Network Ads Accuracy: 0.925
              precision    recall  f1-score   support

           0       0.98      0.90      0.94        52
           1       0.84      0.96      0.90        28

    accuracy                           0.93        80
   macro avg       0.91      0.93      0.92        80
weighted avg       0.93      0.93      0.93        80

Titanic Accuracy: 0.8156424581005587
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       105
           1       0.82      0.72      0.76        74

    accuracy                           0.82       179
   macro avg       0.82      0.80      0.81       179
weighted avg       0.82      0.82      0.81       179

Diabetes Accuracy: 0.7337662337662337
              precision    recall  f1-score   support

           0       0.77      0.83      0.80        99
           1       0.65      0.56      0.60        55

    accuracy                           0.73       154
   macro avg      

In [12]:
#question 2 apply naive bayes classifier and find accuracy
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score

# 1. Social Network Ads
df = pd.read_csv('Social_Network_Ads.csv')
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
X = df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Social Network Ads Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


# 2. Titanic
df = pd.read_csv('titanic.csv')
df = df[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
df['Sex'] = LabelEncoder().fit_transform(df['Sex'].astype(str))
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'].astype(str))
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df = df.dropna()
X = df.drop('Survived', axis=1).values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Titanic Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


# 3. Diabetes
df = pd.read_csv('diabetes_dataset.csv')
X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Diabetes Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


Social Network Ads Accuracy: 0.9375
              precision    recall  f1-score   support

           0       0.94      0.96      0.95        52
           1       0.93      0.89      0.91        28

    accuracy                           0.94        80
   macro avg       0.93      0.93      0.93        80
weighted avg       0.94      0.94      0.94        80

Titanic Accuracy: 0.776536312849162
              precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179

Diabetes Accuracy: 0.7662337662337663
              precision    recall  f1-score   support

           0       0.83      0.80      0.81        99
           1       0.66      0.71      0.68        55

    accuracy                           0.77       154
   macro avg      

In [1]:
#question 3 - svm from scratch
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

class SVM:
    def __init__(self, lr=0.001, C=1.0, epochs=1000):
        self.lr = lr
        self.C = C
        self.epochs = epochs

    def fit(self, X, y):
        y = np.where(y <= 0, -1, 1)
        n, f = X.shape
        self.w = np.zeros(f)
        self.b = 0
        for _ in range(self.epochs):
            for i in range(n):
                if y[i] * (np.dot(X[i], self.w) + self.b) >= 1:
                    self.w -= self.lr * (2 * self.w)
                else:
                    self.w -= self.lr * (2 * self.w - self.C * y[i] * X[i])
                    self.b += self.lr * self.C * y[i]

    def predict(self, X):
        return np.sign(np.dot(X, self.w) + self.b)

def standard_scale(X_train, X_test):
    mean = X_train.mean(axis=0)
    std  = X_train.std(axis=0) + 1e-8
    return (X_train - mean) / std, (X_test - mean) / std

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

def classification_report(y_true, y_pred):
    classes = np.unique(y_true)
    print(f"{'':>12} {'precision':>10} {'recall':>10} {'f1-score':>10} {'support':>10}")
    for c in classes:
        tp = np.sum((y_pred == c) & (y_true == c))
        fp = np.sum((y_pred == c) & (y_true != c))
        fn = np.sum((y_pred != c) & (y_true == c))
        precision = tp / (tp + fp + 1e-8)
        recall    = tp / (tp + fn + 1e-8)
        f1        = 2 * precision * recall / (precision + recall + 1e-8)
        support   = np.sum(y_true == c)
        print(f"{c:>12} {precision:>10.2f} {recall:>10.2f} {f1:>10.2f} {support:>10}")
    print(f"\n{'accuracy':>12} {'':>10} {'':>10} {accuracy(y_true, y_pred):>10.2f} {len(y_true):>10}")

def confusion_matrix(y_true, y_pred):
    classes = np.unique(y_true)
    matrix = np.zeros((len(classes), len(classes)), dtype=int)
    for i, actual in enumerate(classes):
        for j, predicted in enumerate(classes):
            matrix[i][j] = np.sum((y_true == actual) & (y_pred == predicted))
    return matrix


# 1. Social Network Ads
df = pd.read_csv('Social_Network_Ads.csv')
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
X = df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)
y_train_s = np.where(y_train <= 0, -1, 1)
y_test_s  = np.where(y_test  <= 0, -1, 1)

model = SVM()
model.fit(X_train, y_train_s)
y_pred = model.predict(X_test)

print("Social Network Ads")
print("Accuracy:", accuracy(y_test_s, y_pred))
classification_report(y_test_s, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test_s, y_pred))


# 2. Titanic
df = pd.read_csv('titanic.csv')
df = df[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
df['Sex']      = LabelEncoder().fit_transform(df['Sex'].astype(str))
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'].astype(str))
df['Age']      = df['Age'].fillna(df['Age'].median())
df['Fare']     = df['Fare'].fillna(df['Fare'].median())
df = df.dropna()
X = df.drop('Survived', axis=1).values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)
y_train_s = np.where(y_train <= 0, -1, 1)
y_test_s  = np.where(y_test  <= 0, -1, 1)

model = SVM()
model.fit(X_train, y_train_s)
y_pred = model.predict(X_test)

print("\nTitanic")
print("Accuracy:", accuracy(y_test_s, y_pred))
classification_report(y_test_s, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test_s, y_pred))


# 3. Diabetes
df = pd.read_csv('diabetes_dataset.csv')
X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)
y_train_s = np.where(y_train <= 0, -1, 1)
y_test_s  = np.where(y_test  <= 0, -1, 1)

model = SVM()
model.fit(X_train, y_train_s)
y_pred = model.predict(X_test)

print("\nDiabetes")
print("Accuracy:", accuracy(y_test_s, y_pred))
classification_report(y_test_s, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test_s, y_pred))

Social Network Ads
Accuracy: 0.65
              precision     recall   f1-score    support
          -1       0.65       1.00       0.79         52
           1       0.00       0.00       0.00         28

    accuracy                             0.65         80
Confusion Matrix:
 [[52  0]
 [28  0]]

Titanic
Accuracy: 0.5865921787709497
              precision     recall   f1-score    support
          -1       0.59       1.00       0.74        105
           1       0.00       0.00       0.00         74

    accuracy                             0.59        179
Confusion Matrix:
 [[105   0]
 [ 74   0]]

Diabetes
Accuracy: 0.6428571428571429
              precision     recall   f1-score    support
          -1       0.64       1.00       0.78         99
           1       0.00       0.00       0.00         55

    accuracy                             0.64        154
Confusion Matrix:
 [[99  0]
 [55  0]]


In [2]:
#naive bayes from scratch
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

class GaussianNB:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean    = {}
        self.var     = {}
        self.prior   = {}
        for c in self.classes:
            Xc = X[y == c]
            self.mean[c]  = Xc.mean(axis=0)
            self.var[c]   = Xc.var(axis=0) + 1e-9
            self.prior[c] = len(Xc) / len(y)

    def gaussian(self, x, mean, var):
        return (1 / np.sqrt(2 * np.pi * var)) * np.exp(-((x - mean) ** 2) / (2 * var))

    def predict(self, X):
        preds = []
        for x in X:
            probs = {}
            for c in self.classes:
                likelihood = np.prod(self.gaussian(x, self.mean[c], self.var[c]))
                probs[c] = self.prior[c] * likelihood
            preds.append(max(probs, key=probs.get))
        return np.array(preds)

def standard_scale(X_train, X_test):
    mean = X_train.mean(axis=0)
    std  = X_train.std(axis=0) + 1e-8
    return (X_train - mean) / std, (X_test - mean) / std

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

def classification_report(y_true, y_pred):
    classes = np.unique(y_true)
    print(f"{'':>12} {'precision':>10} {'recall':>10} {'f1-score':>10} {'support':>10}")
    for c in classes:
        tp = np.sum((y_pred == c) & (y_true == c))
        fp = np.sum((y_pred == c) & (y_true != c))
        fn = np.sum((y_pred != c) & (y_true == c))
        precision = tp / (tp + fp + 1e-8)
        recall    = tp / (tp + fn + 1e-8)
        f1        = 2 * precision * recall / (precision + recall + 1e-8)
        support   = np.sum(y_true == c)
        print(f"{c:>12} {precision:>10.2f} {recall:>10.2f} {f1:>10.2f} {support:>10}")
    print(f"\n{'accuracy':>12} {'':>10} {'':>10} {accuracy(y_true, y_pred):>10.2f} {len(y_true):>10}")

def confusion_matrix(y_true, y_pred):
    classes = np.unique(y_true)
    matrix = np.zeros((len(classes), len(classes)), dtype=int)
    for i, actual in enumerate(classes):
        for j, predicted in enumerate(classes):
            matrix[i][j] = np.sum((y_true == actual) & (y_pred == predicted))
    return matrix


# 1. Social Network Ads
df = pd.read_csv('Social_Network_Ads.csv')
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
X = df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Social Network Ads")
print("Accuracy:", accuracy(y_test, y_pred))
classification_report(y_test, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


# 2. Titanic
df = pd.read_csv('titanic.csv')
df = df[['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
df['Sex']      = LabelEncoder().fit_transform(df['Sex'].astype(str))
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'].astype(str))
df['Age']      = df['Age'].fillna(df['Age'].median())
df['Fare']     = df['Fare'].fillna(df['Fare'].median())
df = df.dropna()
X = df.drop('Survived', axis=1).values
y = df['Survived'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\nTitanic")
print("Accuracy:", accuracy(y_test, y_pred))
classification_report(y_test, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


# 3. Diabetes
df = pd.read_csv('diabetes_dataset.csv')
X = df.drop('Outcome', axis=1).values
y = df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test = standard_scale(X_train, X_test)

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\nDiabetes")
print("Accuracy:", accuracy(y_test, y_pred))
classification_report(y_test, y_pred)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Social Network Ads
Accuracy: 0.9375
              precision     recall   f1-score    support
           0       0.94       0.96       0.95         52
           1       0.93       0.89       0.91         28

    accuracy                             0.94         80
Confusion Matrix:
 [[50  2]
 [ 3 25]]

Titanic
Accuracy: 0.776536312849162
              precision     recall   f1-score    support
           0       0.83       0.78       0.80        105
           1       0.71       0.77       0.74         74

    accuracy                             0.78        179
Confusion Matrix:
 [[82 23]
 [17 57]]

Diabetes
Accuracy: 0.7662337662337663
              precision     recall   f1-score    support
           0       0.83       0.80       0.81         99
           1       0.66       0.71       0.68         55

    accuracy                             0.77        154
Confusion Matrix:
 [[79 20]
 [16 39]]
